name: "Deploy to aws"

on: workflow_dispatch

jobs:
    deploy:
        runs-on: self-hosted
        steps:
            - name: "Setup nodejs"
              uses: actions/setup-node@v3
              with:
                node-version: '21'
            - name: "Checkout code"
              uses: actions/checkout@v3

            - name: "Install dependencies"
              run: npm install

            - name: "Install pm2 globally"
              run: npm install pm2 -g
            - name: "Run the tests"
              run: npm test